fix: missing tailwindcss tokens
Andrewnt219/rent-near-me pull request #95
Opened 2021-11-04 21:08 UTC by Andrewnt219

You can read the changes if you want, but I recommend only checking the new UI from preview deployment

2021-11-05 01:03 UTC, vitokhangnguyen requested changes
This is a lot of work. Great job!

2021-11-05 01:03 UTC, vitokhangnguyen commented on src/ui/Text/Text.tsx
> +      as={props.component ?? 'span'}
Default should be `<p>` tag, it's just more intutitive.

2021-11-05 01:15 UTC, Andrewnt219 commented on @types/twin.d.ts
> +import { ComponentProps, VFC } from 'react';
Ah, this is from the 1h debug.

2021-11-05 01:16 UTC, Andrewnt219 commented on package.json
> +    "nanoid": "^3.1.30",
Doesn't seem like we use it anywhere.

2021-11-05 01:16 UTC, vitokhangnguyen commented on package.json
> +    "nanoid": "^3.1.30",
Then we should remove it

2021-11-05 01:17 UTC, Andrewnt219 commented on src/modules/account/components/AccountMenu/AccountMenu.tsx
> +        icon: <Icon icon="mdi:information" tw="text-secondary" />,
Eva, sure.

Why that syntax?

2021-11-05 01:19 UTC, Andrewnt219 commented on src/ui/Modal/Modal.tsx
> -    top: calc(50% - ${theme('spacing.var-app-bar')} / 2);
I think I fixed that already.

2021-11-05 01:19 UTC, Andrewnt219 commented on src/ui/Modal/Modal.tsx
> -  max-height: calc(100vh - ${theme`spacing.var-app-bar`} - 8rem);
I think I fixed that already.

2021-11-05 01:19 UTC, vitokhangnguyen commented on src/modules/account/components/AccountMenu/AccountMenu.tsx
> +        icon: <Icon icon="mdi:information" tw="text-secondary" />,
Importing and passing it in seems better than passing string? 🤔  Unless when we type the string, the library provide intellisense?

2021-11-05 01:20 UTC, vitokhangnguyen commented on src/ui/Modal/Modal.tsx
> -    top: calc(50% - ${theme('spacing.var-app-bar')} / 2);
I'll take your words for it

2021-11-05 01:24 UTC, Andrewnt219 commented on src/modules/account/components/AccountMenu/AccountMenu.tsx
> +        icon: <Icon icon="mdi:information" tw="text-secondary" />,
That's extra work though, it's also a string when we specify the import so I see no difference in risks.

2021-11-05 01:34 UTC, vitokhangnguyen commented on src/modules/account/components/AccountInfoCard/AccountInfoCard.tsx
> +        <Text component="span" aria-hidden tw="text-[length:2.5em]">
I'm thinking if it's not actually text, let's not use the `<Text>` componenet

2021-11-05 02:21 UTC, vitokhangnguyen requested changes
Styling suggestion: The shadow of the navbar should be more prominenet. Besides that, the UI quality seems impreoved by a lot with thje new sstyle system

![image](https://user-images.githubusercontent.com/54929186/140447575-94a06057-56ac-4992-a89c-3de6b4df44d6.png)

![image](https://user-images.githubusercontent.com/54929186/140447602-d1f1248a-d7b9-4d2e-bc7a-ad1f078191c8.png)

2021-11-05 05:17 UTC, vitokhangnguyen commented
Ehhh... not sure if you're done but the logo is different now

![image](https://user-images.githubusercontent.com/54929186/140461963-bf94879b-3654-4b70-9be1-db31a6852aad.png)

2021-11-05 14:00 UTC, Andrewnt219 commented
@vitokhangnguyen Reverted.

2021-11-05 20:50 UTC, vitokhangnguyen requested changes

2021-11-05 20:50 UTC, vitokhangnguyen commented on src/modules/user-auth/components/LoginForm/LoginForm.tsx
> +              <Icon icon={googleFill} tw="text-muted" />
Let's use the icons in [this set](https://icon-sets.iconify.design/logos/) for Google, Facebook logo

2021-11-06 04:18 UTC, vitokhangnguyen approved these changes
Just made a small change to use the Airbnb logo for the "Create a new account" button in the LoginForm. This's gonna be the placeholder for our logo when we have one.

2021-11-06 04:38 UTC, merged